namespace VisualStudio_DesignPatternsInCSharp.StructuralDesignPatterns.CompositeDesignPattern.CompositeSpecificationDesignPattern
{
    using System.Collections.Generic;

    public abstract class TemplateCompositeSpecificationWithCompositeSpecification<TTemplateComponentWithCompositeSpecification>(params TemplateSpecificationWithCompositeSpecification<TTemplateComponentWithCompositeSpecification>[] newTemplateCompositeSpecificationTemplateSpecificationCollectionToInitialize) : TemplateSpecificationWithCompositeSpecification<TTemplateComponentWithCompositeSpecification>()
    {
        protected IEnumerable<TemplateSpecificationWithCompositeSpecification<TTemplateComponentWithCompositeSpecification>> TemplateCompositeSpecificationTemplateSpecificationCollection { get; set; } = newTemplateCompositeSpecificationTemplateSpecificationCollectionToInitialize;
    }
}